### ISSUE TITLE
Readme typo

### ISSUE THREAD

**Issue by cspeer** [tubbo/activestorage-audio#1]
Hi there,

thanks a bunch for this gem!
I noticed in your `README.md` you refer to your gem as `active_storage-audio` when it's actually `activestorage-audio` :)

Cheers,
Chris

**Comment by tubbo** [comment]
hey thanks for letting me know! just fixed it.

fun fact: it would have taken you less time to just have fixed the one-char typo and sent me a PR than it did to type out this entire issue.
